f5cs_username: ""
f5cs_password: ""

service_instance_name: "Delegate Zone Name" # gslb.example.com
lbr_name: "Load Balance Record Name" # wwwserver
lbr_aliases: "Any Aliases" # www
virtual_servers: "Virtual Server Name" # vsIsp
pools: "Pool Name" # isppool
monitors: "ICMP" # Ping 

checkInterval: 86400 #seconds (24 hours)

ip_query: "https://ifconfig.io/ip"
#  - "https://api.ipify.org"
#  - "https://ident.me/"
#  - "https://ifconfig.me/ip"
#  - "https://icanhazip.com/"
